# ###
# old:
#
# FIND_FILE(DPMJET_OBJECT NAMES dpmjet3.0-5.o PATHS $ENV{DPMJETDIR})
# FIND_FILE(DPMJET_PY_OBJECT NAMES pythia6115dpm3v1.o PATHS $ENV{DPMJETDIR})
# FIND_FILE(DPMJET_PHO_OBJECT NAMES phojet1.12-35c4.o PATHS $ENV{DPMJETDIR})
#
# IF (DPMJET_OBJECT AND DPMJET_PY_OBJECT AND DPMJET_PHO_OBJECT) 
#    SET(DPMJET_OBJECTS ${DPMJET_OBJECT} ${DPMJET_PY_OBJECT} ${DPMJET_PHO_OBJECT})
#    SET(DPMJET_FOUND TRUE)
#    SET_SOURCE_FILES_PROPERTIES(
#       ${DPMJET_OBJECTS}
#       PROPERTIES
#       EXTERNAL_OBJECT true 
#    )
# ENDIF (DPMJET_OBJECT AND DPMJET_PY_OBJECT AND DPMJET_PHO_OBJECT)
#
# ###

# ###
# new (Luan Arbeletche):
#
FIND_LIBRARY(DPMJET_EXTERNAL_LIB NAMES DPMJET PATHS $ENV{DPMJETDIR} $ENV{DPMJETDIR}/lib $ENV{DPMJET_DIR} $ENV{DPMJET_DIR}/lib)
#
IF (DPMJET_EXTERNAL_LIB)
   SET(DPMJET_FOUND TRUE)
ENDIF (DPMJET_EXTERNAL_LIB)
#
# ###

IF (DPMJET_FOUND)
   IF (NOT DPMJet_FIND_QUIETLY)
      # MESSAGE(STATUS "Found DPMJet: ${DPMJET_OBJECT}")
      MESSAGE(STATUS "Found DPMJet: ${DPMJET_EXTERNAL_LIB}")
      # extract the include directory
      # get the directory of the library
      GET_FILENAME_COMPONENT(DPMJET_DIR ${DPMJET_EXTERNAL_LIB} PATH)
      SET(DPMJET_INCLUDE_DIR "${DPMJET_DIR}/include")
      MESSAGE(STATUS "Assuming DPMJet include directory: ${DPMJET_INCLUDE_DIR}")
      # check if the include directory exists
      IF (EXISTS "${DPMJET_INCLUDE_DIR}")
         MESSAGE(STATUS "DPMJet include directory exists: ${DPMJET_INCLUDE_DIR}")
         INCLUDE_DIRECTORIES(${DPMJET_INCLUDE_DIR})
      ELSE (EXISTS "${DPMJET_INCLUDE_DIR}")
         MESSAGE(FATAL_ERROR "DPMJet include directory does not exist: ${DPMJET_INCLUDE_DIR}")
   ENDIF (NOT DPMJet_FIND_QUIETLY)
ELSE (DPMJET_FOUND)
   IF (DPMJet_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find DPMJet, we look in $DPMJETDIR $DPMJET_DIR")
   ELSE(DPMJet_FIND_REQUIRED)
      IF(NOT DPMJet_FIND_QUIETLY)
	 MESSAGE(STATUS "Could not find DPMJet, we look in $DPMJETDIR or $DPMJET_DIR")
      ENDIF(NOT DPMJet_FIND_QUIETLY)
   ENDIF (DPMJet_FIND_REQUIRED)
ENDIF (DPMJET_FOUND)

